---
- name: Log into AWS ECR docker registry
  ansible.builtin.shell: "aws ecr get-login-password | docker login --username AWS --password-stdin {{ aws_ecr_login_repository }}"
  when: aws_ecr_login_repository is not none and aws_ecr_login_repository != ''
